export enum GameType {
  TWO_PLAYER_DUEL = 'Two Player Duel',
  FREE_FOR_ALL = 'Free For All',
  COMMANDER_TWO_PLAYER_DUEL = 'Commander Two Player Duel',
  COMMANDER_FREE_FOR_ALL = 'Commander Free For All',
  TINY_LEADERS_TWO_PLAYER_DUEL = 'Tiny Leaders Two Player Duel',
  CANADIAN_HIGHLANDER_TWO_PLAYER_DUEL = 'Canadian Highlander Two Player Duel',
  PENNY_DREADFUL_COMMANDER_FREE_FOR_ALL = 'Penny Dreadful Commander Free For All',
  FREEFORM_COMMANDER_TWO_PLAYER_DUEL = 'Freeform Commander Two Player Duel',
  FREEFORM_COMMANDER_FREE_FOR_ALL = 'Freeform Commander Free For All',
  FREEFORM_UNLIMITED_COMMANDER = 'Freeform Unlimited Commander',
  CUSTOM_PILLAR_OF_THE_PARUNS_TWO_PLAYER_DUEL = 'Custom Pillar of the Paruns Two Player Duel',
  OATHBREAKER_TWO_PLAYER_DUEL = 'Oathbreaker Two Player Duel',
  OATHBREAKER_FREE_FOR_ALL = 'Oathbreaker Free For All',
  BRAWL_TWO_PLAYER_DUEL = 'Brawl Two Player Duel',
  BRAWL_FREE_FOR_ALL = 'Brawl Free For All',
  MOMIR_BASIC_TWO_PLAYER_DUEL = 'Momir Basic Two Player Duel',
  MOMIR_BASIC_FREE_FOR_ALL = 'Momir Basic Free For All',
}

export enum DeckType {
  STANDARD = 'Constructed - Standard',
  EXTENDED = 'Constructed - Extended',
  FRONTIER = 'Constructed - Frontier',
  PIONEER = 'Constructed - Pioneer',
  MODERN = 'Constructed - Modern',
  MODERN_NO_BANNED_LIST = 'Constructed - Modern - No Banned List',
  ETERNAL = 'Constructed - Eternal',
  LEGACY = 'Constructed - Legacy',
  VINTAGE = 'Constructed - Vintage',
  PAUPER = 'Constructed - Pauper',
  HISTORIC = 'Constructed - Historic',
  HISTORICAL_TYPE_2 = 'Constructed - Historical Type 2',
  SUPER_TYPE_2 = 'Constructed - Super Type 2',
  AUSTRALIAN_HIGHLANDER = 'Constructed - Australian Highlander',
  CANADIAN_HIGHLANDER = 'Constructed - Canadian Highlander',
  EUROPEAN_HIGHLANDER = 'Constructed - European Highlander',
  OLD_SCHOOL_9394 = 'Constructed - Old School 93/94',
  OLD_SCHOOL_9394_ITALIAN = 'Constructed - Old School 93/94 - Italian Rules',
  OLD_SCHOOL_9394_CFB = 'Constructed - Old School 93/94 - Channel Fireball Rules',
  OLD_SCHOOL_9394_EUDOGAMES = 'Constructed - Old School 93/94 - EudoGames Rules',
  OLD_SCHOOL_9394_EC = 'Constructed - Old School 93/94 - EC Rules',
  PREMODERN = 'Constructed - Premodern',
  FREEFORM = 'Constructed - Freeform',
  FREEFORM_UNLIMITED = 'Constructed - Freeform Unlimited',
  COMMANDER = 'Variant Magic - Commander',
  DUEL_COMMANDER = 'Variant Magic - Duel Commander',
  MTGO_1V1_COMMANDER = 'Variant Magic - MTGO 1v1 Commander',
  CENTURION_COMMANDER = 'Variant Magic - Centurion Commander',
  TINY_LEADERS = 'Variant Magic - Tiny Leaders',
  MOMIR_BASIC = 'Variant Magic - Momir Basic',
  PENNY_DREADFUL_COMMANDER = 'Variant Magic - Penny Dreadful Commander',
  FREEFORM_COMMANDER = 'Variant Magic - Freeform Commander',
  FREEFORM_UNLIMITED_COMMANDER = 'Variant Magic - Freeform Unlimited Commander',
  BRAWL = 'Variant Magic - Brawl',
  OATHBREAKER = 'Variant Magic - Oathbreaker',
  LIMITED = 'Limited',
}
